# Site settings
title: Michel Orgaz
email: postmater@michelorgaz.com
description: > # this means to ignore newlines until "baseurl:"
  Michel Orgaz website and blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://michelorgaz.com" # the base hostname & protocol for your site
twitter_username: michelorgaz
github_username:  michelorgaz

# Build settings
markdown: kramdown
